"""Schema migration: switch permits uniqueness from (project_no) to
(project_no, permit_code).

Why: the Sold Permits report returns one row per sub-permit (Building,
Electrical, Plumbing, Mechanical, etc.) under the same project_no.
The original schema's UNIQUE constraint on project_no alone drops
~57% of these sub-permits via ON CONFLICT DO NOTHING. With a composite
key, every sub-permit is preserved.

Safety:
- Idempotent: re-runs do nothing if migration already applied.
- Wrapped in a transaction; rolls back on any failure.
- Existing rows get permit_code = 'LEGACY' (unique per project_no, so
  the composite constraint stays satisfied even before we re-scrape).
- Dry-run mode prints the planned SQL without executing.

Run from `backend/`:
    python -m scripts.migrate_composite_key            # dry-run
    python -m scripts.migrate_composite_key --apply    # execute
    python -m scripts.migrate_composite_key --status   # show current state
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import inspect, text  # noqa: E402

from db import engine  # noqa: E402


MIGRATION_SQL = [
    # 1. Add permit_code column (nullable so the ALTER is fast on big tables)
    "ALTER TABLE permits ADD COLUMN IF NOT EXISTS permit_code VARCHAR",

    # 2. Backfill existing rows with a placeholder so the new composite
    #    constraint is satisfiable. 'LEGACY' is unique per project_no since
    #    each project currently has only 1 row, so no conflicts arise.
    "UPDATE permits SET permit_code = 'LEGACY' WHERE permit_code IS NULL",

    # 3. Make permit_code NOT NULL — required so the composite unique
    #    constraint actually deduplicates (Postgres treats NULL as distinct).
    "ALTER TABLE permits ALTER COLUMN permit_code SET NOT NULL",

    # 4. Drop the existing project_no UNIQUE constraint. The autogenerated
    #    name follows SQLAlchemy's convention: '<table>_<column>_key'.
    "ALTER TABLE permits DROP CONSTRAINT IF EXISTS permits_project_no_key",

    # 5. Drop the unique index on project_no (SQLAlchemy's unique=True creates
    #    one). Recreate as plain index so queries by project_no stay fast.
    "DROP INDEX IF EXISTS ix_permits_project_no",
    "CREATE INDEX IF NOT EXISTS ix_permits_project_no ON permits(project_no)",

    # 6. Add the composite unique constraint — the load-bearing change.
    "ALTER TABLE permits ADD CONSTRAINT uq_project_permit "
    "UNIQUE (project_no, permit_code)",

    # 7. Index permit_code on its own for filtering.
    "CREATE INDEX IF NOT EXISTS ix_permits_permit_code ON permits(permit_code)",
]


def show_status():
    insp = inspect(engine)
    cols = {c["name"]: c for c in insp.get_columns("permits")}
    print(f"permits table — {len(cols)} columns")
    print(f"  has permit_code column: {'permit_code' in cols}")
    if "permit_code" in cols:
        print(f"  permit_code nullable:    {cols['permit_code'].get('nullable')}")
    print()

    uniques = insp.get_unique_constraints("permits")
    print(f"Unique constraints ({len(uniques)}):")
    for u in uniques:
        print(f"  {u.get('name')}: {u.get('column_names')}")

    indexes = insp.get_indexes("permits")
    print(f"Indexes ({len(indexes)}):")
    for i in indexes:
        flag = " UNIQUE" if i.get("unique") else ""
        print(f"  {i.get('name')}: {i.get('column_names')}{flag}")


def is_migrated() -> bool:
    """Detect whether migration has already run."""
    insp = inspect(engine)
    cols = {c["name"] for c in insp.get_columns("permits")}
    if "permit_code" not in cols:
        return False
    for u in insp.get_unique_constraints("permits"):
        if set(u.get("column_names", [])) == {"project_no", "permit_code"}:
            return True
    return False


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--apply", action="store_true", help="Execute the migration")
    p.add_argument("--status", action="store_true", help="Show current schema only")
    args = p.parse_args()

    if args.status:
        show_status()
        return

    print("Current state:")
    show_status()
    print()

    if is_migrated():
        print("✓ Migration already applied. Nothing to do.")
        return

    print("Planned SQL:")
    for stmt in MIGRATION_SQL:
        print(f"  - {stmt}")
    print()

    if not args.apply:
        print("Dry-run. Re-run with --apply to execute.")
        return

    print("Executing migration in a single transaction...")
    with engine.begin() as conn:
        for stmt in MIGRATION_SQL:
            print(f"  · {stmt[:80]}...")
            conn.execute(text(stmt))
    print()
    print("✓ Migration complete. New state:")
    show_status()


if __name__ == "__main__":
    main()
